application.name: drawings

drawings:
  palettes:
    - FD3F33, 4369B2, FFC13A
    - E63946, F1FAEE, A8DADC, 457B9D, 1D3557
    - f7c59f, 2a324b, 767b91, c7ccdb, e1e5ee
    - 2b2d42, 8d99ae, edf2f4, ef233c, d90429

server:
  compression:
    enabled: true
    mime-types: application/json,application/javascript,text/html
    min-response-size: 1024